[2025-07-23T07:52:56.130+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T07:52:55.017118+00:00 [queued]>
[2025-07-23T07:52:56.136+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T07:52:55.017118+00:00 [queued]>
[2025-07-23T07:52:56.136+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T07:52:56.145+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_transform_load_coindesk> on 2025-07-23 07:52:55.017118+00:00
[2025-07-23T07:52:56.153+0000] {standard_task_runner.py:60} INFO - Started process 235 to run task
[2025-07-23T07:52:56.156+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'coindesk_bitcoin_etl', 'extract_transform_load_coindesk', 'manual__2025-07-23T07:52:55.017118+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/coindesk_etl_dag.py', '--cfg-path', '/tmp/tmpe24cqu51']
[2025-07-23T07:52:56.158+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask extract_transform_load_coindesk
[2025-07-23T07:52:56.195+0000] {task_command.py:423} INFO - Running <TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T07:52:55.017118+00:00 [running]> on host 7896427c6261
[2025-07-23T07:52:56.257+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='coindesk_bitcoin_etl' AIRFLOW_CTX_TASK_ID='extract_transform_load_coindesk' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T07:52:55.017118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-23T07:52:55.017118+00:00'
[2025-07-23T07:52:56.322+0000] {logging_mixin.py:188} INFO - Error en ETL CoinDesk: HTTPSConnectionPool(host='api.coindesk.com', port=443): Max retries exceeded with url: /v1/bpi/currentprice.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ca4794e64d0>: Failed to resolve 'api.coindesk.com' ([Errno -2] Name or service not known)"))
[2025-07-23T07:52:56.323+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-23T07:52:56.331+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=coindesk_bitcoin_etl, task_id=extract_transform_load_coindesk, execution_date=20250723T075255, start_date=20250723T075256, end_date=20250723T075256
[2025-07-23T07:52:56.368+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-23T07:52:56.387+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
