[2025-07-23T08:12:27.441+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T08:12:26.742658+00:00 [queued]>
[2025-07-23T08:12:27.446+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T08:12:26.742658+00:00 [queued]>
[2025-07-23T08:12:27.446+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T08:12:27.455+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_transform_load_coindesk> on 2025-07-23 08:12:26.742658+00:00
[2025-07-23T08:12:27.460+0000] {standard_task_runner.py:60} INFO - Started process 675 to run task
[2025-07-23T08:12:27.464+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'coindesk_bitcoin_etl', 'extract_transform_load_coindesk', 'manual__2025-07-23T08:12:26.742658+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/coindesk_etl_dag.py', '--cfg-path', '/tmp/tmpof_pnlwi']
[2025-07-23T08:12:27.466+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask extract_transform_load_coindesk
[2025-07-23T08:12:27.507+0000] {task_command.py:423} INFO - Running <TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk manual__2025-07-23T08:12:26.742658+00:00 [running]> on host a1bf3f9b22c7
[2025-07-23T08:12:27.568+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='coindesk_bitcoin_etl' AIRFLOW_CTX_TASK_ID='extract_transform_load_coindesk' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T08:12:26.742658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-23T08:12:26.742658+00:00'
[2025-07-23T08:12:27.646+0000] {logging_mixin.py:188} INFO - Error en ETL CoinDesk: HTTPSConnectionPool(host='api.coindesk.com', port=443): Max retries exceeded with url: /v1/bpi/currentprice.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x759b4fcf2770>: Failed to resolve 'api.coindesk.com' ([Errno -2] Name or service not known)"))
[2025-07-23T08:12:27.646+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-23T08:12:27.654+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=coindesk_bitcoin_etl, task_id=extract_transform_load_coindesk, execution_date=20250723T081226, start_date=20250723T081227, end_date=20250723T081227
[2025-07-23T08:12:27.676+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-23T08:12:27.689+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
