[2025-07-23T08:00:00.571+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk scheduled__2025-07-23T07:00:00+00:00 [queued]>
[2025-07-23T08:00:00.577+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk scheduled__2025-07-23T07:00:00+00:00 [queued]>
[2025-07-23T08:00:00.577+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-23T08:00:00.585+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_transform_load_coindesk> on 2025-07-23 07:00:00+00:00
[2025-07-23T08:00:00.590+0000] {standard_task_runner.py:60} INFO - Started process 754 to run task
[2025-07-23T08:00:00.595+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'coindesk_bitcoin_etl', 'extract_transform_load_coindesk', 'scheduled__2025-07-23T07:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/coindesk_etl_dag.py', '--cfg-path', '/tmp/tmpb_a_d5zo']
[2025-07-23T08:00:00.597+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask extract_transform_load_coindesk
[2025-07-23T08:00:00.637+0000] {task_command.py:423} INFO - Running <TaskInstance: coindesk_bitcoin_etl.extract_transform_load_coindesk scheduled__2025-07-23T07:00:00+00:00 [running]> on host 7896427c6261
[2025-07-23T08:00:00.695+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='coindesk_bitcoin_etl' AIRFLOW_CTX_TASK_ID='extract_transform_load_coindesk' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-23T07:00:00+00:00'
[2025-07-23T08:00:00.808+0000] {logging_mixin.py:188} INFO - Error en ETL CoinDesk: HTTPSConnectionPool(host='api.coindesk.com', port=443): Max retries exceeded with url: /v1/bpi/currentprice.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ca4794ea5f0>: Failed to resolve 'api.coindesk.com' ([Errno -2] Name or service not known)"))
[2025-07-23T08:00:00.808+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-23T08:00:00.815+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=coindesk_bitcoin_etl, task_id=extract_transform_load_coindesk, execution_date=20250723T070000, start_date=20250723T080000, end_date=20250723T080000
[2025-07-23T08:00:00.846+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-23T08:00:00.858+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
